language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install: cp .travis/settings.xml $HOME/.m2/settings.xml

deploy:
  provider: script
  script: mvn -DskipTests deploy
  on:
    tags: true
